version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci3_web
    ports:
      - "${PORT_CI}:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - APP_URL=${APP_URL}
      - DB_HOST=db
      - DB_NAME=codeigniter
      - DB_USER=ci_user
      - DB_PASS=ci_password

  db:
    image: mariadb:10.5
    container_name: ci3_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


