version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci3_web
    ports:
      - "7700:80"
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=codeigniter
      - DB_USER=ci_user
      - DB_PASS=ci_password
    networks:
      - ci3_network

  db:
    image: mariadb:11
    container_name: ci3_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci3_network

  phpmyadmin:
    image: phpmyadmin
    container_name: ci3_phpmyadmin
    restart: always
    ports:
      - "7701:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - ci3_network

volumes:
  db_data:

networks:
  ci3_network:
    driver: bridge