version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci3_web
    ports:
      - "${PORT_CI}:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - APP_URL=${APP_URL}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
