version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci3_web
    ports:
      - "${PORT}:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - coolify
    environment:
      - APP_URL=${APP_URL}
      - DB_HOST=kssw8soc4040occ80ksookgw
      - DB_NAME=djadol
      - DB_USER=mariadb
      - DB_PASS=XzA42BqUUq3E9YRm7OYVfGBB4t5u2tsgKcpwtlWHAFIwdqce6W0pnQZnrlVW8JwA

networks:
  coolify:
    external: true
