@token = b750a78fa2e6f3e55dc6991eb4abdc861e43c4eaa93a557bcd04cc531b47b20d
@host = https://kirim.kopicode.com/index.php/api
@host2 = https://kirim.kopicode.com/index.php/api_masterdetil
###

POST {{host}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=sales1&&password=sales1
###


POST {{host}}/form_action
token: {{token}}
Content-Type: application/x-www-form-urlencoded

form_id=41&&absen_lattitude=8198277&&absen_longitude=276183612786
###


POST {{host}}/form_action
token: {{token}}
Content-Type: application/x-www-form-urlencoded

form_id=42&&absen_lattitude=8198277&&absen_longitude=276183612786
###
//test toko retail
POST {{host}}/form_action
token: {{token}}
Content-Type: application/x-www-form-urlencoded

form_id=31&&name=tokoabc&&location_lat=276183612786&&location_long=276112786
### 

//test jurnal agen
POST {{host}}/form_action
token: {{token}}
Content-Type: application/x-www-form-urlencoded

form_id=33&&count=10&&retail_id=1&&product_id=4
### 
//test master jurnal
POST {{host2}}/form_action
token: {{token}}
content-type: application/json

{
    "": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
todo : after input jurnal_stock, isi harga, isi subtotal, dan aksi terhadap jurnal agen sales