@host=http://localhost:8000/index.php
@token=c8e39086629c6d1c68001c2de8294d5b4a1ec9d62f7c7e6b0ebd8cfbf2e71f0b

###
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=sales1
&password=sales1

###
POST {{host}}/api/form_action
token : {{token}}
Content-Type: application/x-www-form-urlencoded

form_id=43
&retail_id=3
&status=out
&latlong=-7.0782667,113.0989033
&is_new=1

