@host=http://localhost:8000/index.php
@token=cfc16690c0f35e1905d8397dbd2461aca3e1a73eca86d6e70a1862053a50087a

###Login User Sales
POST {{host}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=sales1
&password=sales1

###Kunjungan Form Retail Out
POST {{host}}/api/form_action
token : {{token}}
Content-Type: application/x-www-form-urlencoded

form_id=43
&retail_id=3
&status=out
&latlong=-7.0782667,112.0989033
&is_new=1

